### ISSUE TITLE
Help Me PLEASE

### ISSUE THREAD

**Issue by cattvik24** [BhaskarPanja93/Adfly-View-Bot-Client#13]
ok i downloaded the files, effected signup, i boot and log into the script, it recognizes the virtual machine i see address (MAC),
but i see virtual machine immobile with windscribe logged in..connected, but no rotation, does not open browser , i see nothing ..
![cc](https://user-images.githubusercontent.com/79007183/181482662-cf2e7835-0254-4a19-b9eb-29d82a34f5e8.png)

**Comment by Dec1lent** [comment]
I've had this issue before, I fixed it by resetting the vm window (or just reinstall the vm,) and dont change the resolution afterwards. Also don't buy Windscribe pro, since Bhaska is soon done with making proxies. You can check it out in the `beta_3` file.

If you have any questions or ideas to the bot, head over to [This discussion](https://github.com/BhaskarPanja93/Adfly-View-Bot-Client/discussions/9)

**Comment by BhaskarPanja93** [comment]
Thank you @Dec1lent for the help, and yes he is right. Make sure to runt he VM atleast at 720p (1280x720).
Steps for the following (kindly try to understand in your language):
1> Click "View"
![image](https://user-images.githubusercontent.com/101955196/182023152-8890e5d9-c2ae-4528-819f-98659b5ce943.png)

2> Click Virtual Screen 1 and select anything above 1280x720
![image](https://user-images.githubusercontent.com/101955196/182023242-14fde0cc-da8b-42f2-b565-56f5ced42130.png)

Check if this fixes things, If it still doesn't, Kindly reply or Join us here: https://github.com/BhaskarPanja93/Adfly-View-Bot-Client/discussions/9

**Comment by BhaskarPanja93** [comment]
Closing this issue Because of lack of response from issuer.
