### ISSUE TITLE
What I have changed on the vm.

### ISSUE THREAD

**Issue by Dec1lent** [BhaskarPanja93/Adfly-View-Bot-Client#7]
**I have made a few changes to the vm and im gonna share them with you.**
1. I installed [Mem reduct](https://www.henrypp.org/product/memreduct) and sat it to free ram from programs that might not need all the ram that it had occupied. Set it to clean up every 3-5 minutes, so the programs dont have to constantly load from ssd's to ram which reduces the lifespan of the ssd, and also so the cpu wont spike up every minute.
2. disable antimalware service executable, it has another name on Windows server, I just dont remember.
3. [Amp browser extension](https://github.com/niutech/amp-browser-extension) claims to reduce bandwith up to 40%, but I only see it reducing it by about 15-20%, still bandwith. They also claim that it protects privacy and blocks ads, but the earnings havent been falling since I installed it.
4. I also converted your vm to run in hypervisor (build in to windows pro), which in my opinionis easier to use and has more advanced settings.
5. I did smaller things, like making the windows background a single color and deleting the files in %temp% every 15 minutes.
6. Also if you enable 2-factor-auth, you can add up to 6 vms on the same account, each day.

With these changes im running the vm on 2 vcpu's with Max vcpu usage at 50%, as well as minium memory at 256 Megabytes and maximum at 768 Megabytes. I also have a single 240 gb ssd, for only vm's I dont care if it reads/writes till it dies (it costs 45$ with shipping.)

**Things I would like to change:**
1. It is highly unlikely that Adf.ly gets data about its viewers from Youtube after the view, so it would be nice to just force youtube to not load Javascript at all, to save bandwith and time.
2. I have not tested this with your bot, but on my own simplified bot I can disable images from being loaded and I will still gain push-ads and viewers without getting banned. This will improve basically everything on the vm, in terms of performance and bandwith.
3. It would be nice if the host page list doesnt include the real ip address, though it isnt likely that people here will do something with it and we can just ask our ISP's for a new public ip.
4. I see what you are planning on release 3.x.x, so I wont address those two points I was about to write.
5. Ofcourse better earnings, but it is scalable, so isnt that big of a problem.
7. If I have a new account on a single vm, it will get banned within 2 days, but on an account that I had previouslyused on my bot, doesnt get banned, even if I have 4 vm's to that single adf.ly id.

That was it (or should I say much?) I have allocated 16 gb ram to my server and it can run roughly 20 vms. Though im only getting 3-5$ a day on all of my accounts in total. I hope this project continues and doesnt end like 3/4 of the other projects on this platform (which it doesnt seem like.) Have a nice day :D

**Comment by BhaskarPanja93** [comment]
1. I have heard about Mem Reduct, I avoided it because technically it could stop any of my processes, also windows Server is capable of managing RAM, If you noticed, i allocated 1.2GB RAM and 2vCPUs to each VM, the magic here is, you can go lower and things will still work. 
Try running the VMs with 0.5GB RAM and a single vCPU at 50% cap  :)
2. Since I had a lot of CPU and RAM in my host PC, i didnt care about VM services, because 'antimalware service executable' alone doesnt take much resources 24x7, just when the VM starts up. 
3.  I didnt pay much attention to bandwidth because i expected everyone to have unlimited data, on an average each VM takes 50-100 kilobits per second for the 1st 30seconds(when it refreshes the image files), then takes 5-10 kilobits per second after. Might try Amp after i try on the beta clients.
4. Hyper-V is a feature available only to Windows Server users and Pro users, which is pretty rare. Also one more reason i used VirtualBox is, in a week i will add a new system for client side, which wll allow you users to automatically or manually start or poweroff the VMs from anywhere remotely. Also you can set a particular host sysem RAM value to reach after which VMs will start to shutdown and all. Wait for it. For that you will need the VMs run in VirtualBox.
5. This code is still in beta, so users will need to redownload new versions of the Client VM pretty frequently, I dont think temp folder will fill up so easily. Also i will then implement this temp cleaning process the next bigger update whenever it is. Also the background image, i kinda like the wallpaper :) so i left it, a static imagei dont think would cause much issue.
6. Not sure about what account you are talking about, assuming its Windscribe, well, i would prefer using fake disposable emails because then you can make infinite number  of accounts.

1. Nope adf.ly cant get any data from youtube, because its just a browsing rule. I can change the destination from youtube to my own website and change the code accordinly, which has no scripts, nothing, not sure if bandwidth is a big deal. If it is, i will re-write the code so it takes less bandwidth. I dont think 20kbps is a lot, so.
2. I think i can find extensions that block images, might add them, i didnt do that because i didnt want to get banned.
3. I will hide the real IPs, not a problem.
6. At this point i dont care much about efficiency and adding new features, my main aim now is to fix whatever is causing new IDs to get banned, I checked only those IDs which dont have any payment history are getting banned, rest arent. Not sure why. 
As of now with 3 accounts, and 4 VMs running 24x7, i am earning 3-5$ a day total. Also i am pretty sure this project wont close like my previous bot, because this one literally makes human clicks, no way for AdFly to know it is automated. Also active users motivates me to keep improving the code.
